#
# ROS image for Sawyer development
#

# ***
# *** Sample Docker commands
# ***

# Run the following command from the same directory as the Dockerfile
# > docker build --squash -t robotchallenge:latest .

# verify docker version
# > docker version

# To run the new image and create a container in interactive mode )-it)
# > docker run -it robotchallenge

# LIST all Containers
# > docker ps -a

# DELETE the CONTAINER ( if status is exited)
# > docker rm $(docker ps -a -f status=exited -q)

# LIST all Images
# > docker image ls

# DELETE Images all images
# > docker rmi $(docker images -a -q)

# ***
# *** End Sample Docker Commands
# ***

# Pull base image.
FROM ubuntu:16.04

LABEL author "Paul Stubbs (pstubbs@microsoft.com)"
LABEL description "Microsoft Robot Challenge 2018"
LABEL version "0.0"

# ARGS
#https://en.wikipedia.org/wiki/Marvin_the_Paranoid_Android
ARG username="marvin"
ARG password="BigHero6"
ARG groupname="robotgroup"
ARG groupid="1024"
ARG userid="1024"


# Create the user account
RUN echo '***\n***\n***\n***\nCreate the user account\n***\n***\n***\n***'

RUN groupadd -g ${groupid} ${groupname} && \
    useradd --shell /bin/bash --password ${password} --gid ${groupname} --groups sudo --create-home ${username}

USER ${username}
WORKDIR /home/${username}
RUN HOME=/home/${username}

# Run in noninteractive mode to supress some prompts
ENV DEBIAN_FRONTEND noninteractive

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]

###
USER root
###

# Update to lateset software lists
RUN echo '***\n***\n***\n***\nUpdate to lateset software lists\n***\n***\n***\n***'

RUN apt-get update -y

# Install some common CLI tools
RUN apt-get install -y apt-utils wget software-properties-common sudo

#
#
#
# Install ROS
RUN echo '***\n***\n***\n***\nInstall ROS\n***\n***\n***\n***'
#
#
# http://sdk.rethinkrobotics.com/intera/Workstation_Setup




# Configure Ubuntu repositories. Setup sources.list
RUN ["/bin/sh", "-c", "echo \"deb http://packages.ros.org/ros/ubuntu xenial main\" > /etc/apt/sources.list.d/ros-latest.list"]

# Setup keys
RUN apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

# Install ROS Kinetic Desktop FUll
RUN echo '***\n***\n***\n***\n Install ROS Kinetic Desktop FUll \n***\n***\n***\n***'

RUN apt-get update && apt-get install -y ros-kinetic-desktop-full

# Initialize rosdep
RUN rosdep init

###
USER ${username}
###

RUN rosdep update

###
USER root
###

# Install rosinstall
RUN apt-get install python-rosinstall -y

###
USER ${username}
###

#
#
#
# Create Development Workspace
RUN echo '***\n***\n***\n***\nCreate Development Workspace\n***\n***\n***\n***'
#
#
#

# Create ROS Workspace
RUN mkdir -p ~/ros_ws/src && \
    cd ~/ros_ws && \
    source /opt/ros/kinetic/setup.bash && \
    catkin_make

#
#
#
# Install Intera SDK Dependencies
#
#
#

# Install SDK Dependencies
###
USER root
###
# Update to lateset software lists
RUN apt-get update -y

RUN apt-get update && apt-get install -y \
git-core \
python-argparse \
python-wstool \
python-vcstools \
python-rosdep \
ros-kinetic-control-msgs \
ros-kinetic-joystick-drivers \
ros-kinetic-xacro \
ros-kinetic-tf2-ros \
ros-kinetic-rviz \
ros-kinetic-cv-bridge \
ros-kinetic-actionlib \
ros-kinetic-actionlib-msgs \
ros-kinetic-dynamic-reconfigure \
ros-kinetic-trajectory-msgs \
ros-kinetic-rospy-message-converter

###
USER ${username}
###

#
#
#
# Install Intera Robot SDK
#
#
#

RUN cd ~/ros_ws/src && \
    wstool init . && \
    git clone https://github.com/RethinkRobotics/sawyer_robot.git && \
    wstool merge sawyer_robot/sawyer_robot.rosinstall && \
    wstool update

# Source ROS Setup
RUN cd ~/ros_ws && \
    source /opt/ros/kinetic/setup.bash && \
    catkin_make

#
#
#
# Configure Robot Communication/ROS Workspace
#
#
#

# Copy the intera.sh script
# The intera.sh file already exists in intera_sdk repo, 
# copy the file into your ros workspace.
RUN cp ~/ros_ws/src/intera_sdk/intera.sh ~/ros_ws

# Update the copy of the intera.sh file
# RUN cd ~/ros_ws
# Update ROS Distribution
RUN sed -i 's/ros_version="indigo"/ros_version="kinetic"/' ~/ros_ws/intera.sh
# Update the ROBOTS hostname
RUN sed -i 's/robot_hostname="robot_hostname.local"/robot_hostname="paule.local"/' ~/ros_ws/intera.sh

# TODO:// Need to figure out the docker networking to resolve hostname
# Update YOUR IP or Hostname. This must be resolvable to the Robot
# Choose one. Be sure to add or remove the leading # from the right ones
RUN sed -i 's/your_ip="192.168.XXX.XXX"/your_ip="192.168.XXX.XXX"/' ~/ros_ws/intera.sh
#RUN sed -i 's/#your_hostname="my_computer.local"/your_hostname="my_computer.local"/' intera.sh

# Setup and configure RVIZ
# TODO:// need to find a way to do this from the dockerfile


# http://sdk.rethinkrobotics.com/intera/Gazebo_Tutorial
#
#
#
# Configure Sawyer with Gazebo
#
#
#

# Install Prerequisites
###
USER root
###
# Update to lateset software lists

RUN apt-get update && apt-get install -y  \
    gazebo7  \
    ros-kinetic-qt-build  \
    ros-kinetic-gazebo-ros-control  \
    ros-kinetic-gazebo-ros-pkgs  \
    ros-kinetic-ros-control  \
    ros-kinetic-control-toolbox  \
    ros-kinetic-realtime-tools  \
    ros-kinetic-ros-controllers  \
    ros-kinetic-xacro  \
    python-wstool  \
    ros-kinetic-tf-conversions  \
    ros-kinetic-kdl-parser  \
    ros-kinetic-sns-ik-lib

###
USER ${username}
###

# Install Sawyer Simulator files
RUN cd ~/ros_ws/src && \
    git clone https://github.com/RethinkRobotics/sawyer_simulator.git && \
    source /opt/ros/kinetic/setup.bash && \
    wstool merge sawyer_simulator/sawyer_simulator.rosinstall && \
    wstool update

# Build the Sources
RUN source /opt/ros/kinetic/setup.bash && \
    cd ~/ros_ws && \
    catkin_make
#
#
#
# Install other tools
#
#
#

###
USER root
###

#Add the path to ROS
RUN echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc

# Clean up all the temp files
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# TODO:// install VSCode